### ISSUE TITLE
Download data for EEG StudyTemplate

### ISSUE THREAD

**Issue by agahkarakuzu** [neurolibre/info#2]
PLEASE ANSWER THE FOLLOWING QUESTIONS 

1. 📂 Which preprint repository will use this dataset for a NeuroLibre submission?

https://github.com/agahkarakuzu/StudyTemplate

2. 📄 Does the repository contain a binder/data_requirements.json file?

✅ Yes

3. 🔗 Please provide a download Link:

Google drive stuff

4. 🫣 What is the data size (please indicate the size after decompression):

🟠 500 - 2048 MB

**Comment by agahkarakuzu** [comment]
@roboneuro cache data for https://github.com/agahkarakuzu/StudyTemplate

**Comment by roboneuro** [comment]
Pinging roboneuro to download the data for agahkarakuzu/StudyTemplate

**Comment by agahkarakuzu** [comment]
@roboneuro cache data for https://github.com/agahkarakuzu/StudyTemplate

**Comment by agahkarakuzu** [comment]
@roboneuro cache data for https://github.com/agahkarakuzu/StudyTemplate

**Comment by roboneuro** [comment]
Pinging roboneuro to download the data for agahkarakuzu/StudyTemplate

**Comment by agahkarakuzu** [comment]
<img width="485" alt="image" src="https://github.com/user-attachments/assets/5f9e0db7-17ad-44c8-93dd-ff9ef7836f33" />

**Comment by agahkarakuzu** [comment]
@roboneuro cache data for https://github.com/agahkarakuzu/StudyTemplate

**Comment by roboneuro** [comment]
Pinging roboneuro to download the data for agahkarakuzu/StudyTemplate

**Comment by agahkarakuzu** [comment]
Lol it responded to the wrong repo.
<img width="941" alt="image" src="https://github.com/user-attachments/assets/f0ecdc80-a5ee-429d-80e5-023119bf8f12" />

**Comment by agahkarakuzu** [comment]
@roboneuro cache data for https://github.com/agahkarakuzu/StudyTemplate

**Comment by roboneuro** [comment]
Pinging roboneuro to download the data for agahkarakuzu/StudyTemplate

**Comment by agahkarakuzu** [comment]
@roboneuro cache data for https://github.com/agahkarakuzu/StudyTemplate

**Comment by roboneuro** [comment]
Pinging roboneuro to download the data for agahkarakuzu/StudyTemplate

**Comment by agahkarakuzu** [comment]
@roboneuro cache data for https://github.com/agahkarakuzu/StudyTemplate

**Comment by roboneuro** [comment]
Pinging roboneuro to download the data for agahkarakuzu/StudyTemplate

**Comment by agahkarakuzu** [comment]
@roboneuro cache data for https://github.com/agahkarakuzu/StudyTemplate

**Comment by roboneuro** [comment]
Pinging roboneuro to download the data for agahkarakuzu/StudyTemplate

**Comment by agahkarakuzu** [comment]
@roboneuro cache data for https://github.com/agahkarakuzu/StudyTemplate

**Comment by roboneuro** [comment]
Pinging roboneuro to download the data for agahkarakuzu/StudyTemplate

**Comment by agahkarakuzu** [comment]
@roboneuro cache data for https://github.com/agahkarakuzu/StudyTemplate

**Comment by roboneuro** [comment]
Pinging roboneuro to download the data for agahkarakuzu/StudyTemplate

**Comment by agahkarakuzu** [comment]
@roboneuro cache data for https://github.com/agahkarakuzu/StudyTemplate

**Comment by roboneuro** [comment]
Pinging roboneuro to download the data for agahkarakuzu/StudyTemplate

**Comment by agahkarakuzu** [comment]
@roboneuro cache data for https://github.com/agahkarakuzu/StudyTemplate

**Comment by roboneuro** [comment]
&#9899; **DOWNLOAD (CACHE) DATA**
----------------------------
**Status:** Waiting for task assignment
**Last updated:** 2024-12-12 19:30:17 PST

<details><summary> :information_source: See details </summary><pre><code>Awaiting task assignment...</code></pre></details>

**Comment by agahkarakuzu** [comment]
FINALLY!!!
